use serde::Deserialize;

#[derive(Debug, Deserialize)]
#[serde(rename_all = "snake_case")]
pub(in crate::tool::browserctl) enum BrowserCtlAction {
    Health,
    Start,
    Stop,
    Snapshot,
    Goto,
    Back,
    Click,
    Upload,
    Fill,
    Type,
    Press,
    Text,
    Html,
    Eval,
    ClickText,
    FillNative,
    Toggle,
    Screenshot,
    MouseClick,
    KeyboardType,
    KeyboardPress,
    Reload,
    Wait,
    Tabs,
    TabsSelect,
    TabsNew,
    TabsClose,
    Detect,
    NetworkLog,
    Fetch,
    Axios,
    Diagnose,
}
