#!/bin/bash
set -euo pipefail

# This script is used to create an auditable commit with a message from the codetether-agent.
# It stages all changes, runs `git diff --cached` through codetether to generate a commit message,
# then commits and pushes. This allows us to have a clear history of changes made by the agent,
# with descriptive commit messages generated by AI.
# Usage: ./commit.sh

cd "$(dirname "$0")"

# Stage all changes
git add -A

# Check there's something to commit
if git diff --cached --quiet; then
    echo "Nothing to commit."
    exit 0
fi

# Get the staged diff
DIFF="$(git diff --cached --stat; echo '---'; git diff --cached)"

# Ask codetether to generate a commit message
echo "Generating commit message..."
RAW_OUTPUT="$(RUST_LOG=error codetether run "You are a commit message generator. Based on the following git diff, produce ONLY a single-line conventional commit message (type: description). No explanation, no markdown, no quotes. Just the commit message.

${DIFF}" 2>/dev/null)"

# Strip ANSI escape codes, then filter out log/session lines
COMMIT_MSG="$(echo "$RAW_OUTPUT" \
  | sed 's/\x1b\[[0-9;]*m//g' \
  | grep -vE '^\[Session:|^[0-9]{4}-[0-9]{2}-[0-9]{2}T|INFO |WARN |DEBUG |ERROR |^codetether::|Crash reporting|^$' \
  | head -1 \
  | sed 's/^["'\''`]*//;s/["'\''`]*$//' \
  | xargs)"

if [ -z "$COMMIT_MSG" ]; then
    echo "Error: codetether failed to generate a commit message."
    git reset HEAD -- . >/dev/null
    exit 1
fi

echo "Commit message: $COMMIT_MSG"
git commit -m "$COMMIT_MSG"
git push origin main
