#!/bin/bash
set -euo pipefail

# This script is used to create an auditable commit with a message from the codetether-agent.
# It stages all changes, runs `git diff --cached` through codetether to generate a commit message,
# then commits and pushes. This allows us to have a clear history of changes made by the agent,
# with descriptive commit messages generated by AI.
# Usage: ./commit.sh

cd "$(dirname "$0")"

# Stage all changes
git add -A

# Check there's something to commit
if git diff --cached --quiet; then
    echo "Nothing to commit."
    exit 0
fi

# Get the staged diff
DIFF="$(git diff --cached --stat; echo '---'; git diff --cached)"

# Ask codetether to generate a commit message
echo "Generating commit message..."
COMMIT_MSG="$(codetether run "You are a commit message generator. Based on the following git diff, produce ONLY a single-line conventional commit message (type: description). No explanation, no markdown, no quotes. Just the commit message.

${DIFF}")"

# Strip any surrounding quotes or whitespace
COMMIT_MSG="$(echo "$COMMIT_MSG" | head -1 | sed 's/^["'\'']*//;s/["'\'']*$//' | xargs)"

if [ -z "$COMMIT_MSG" ]; then
    echo "Error: codetether failed to generate a commit message."
    git reset HEAD -- . >/dev/null
    exit 1
fi

echo "Commit message: $COMMIT_MSG"
git commit -m "$COMMIT_MSG"
git push origin main
