//! Beacon payload for UDP LAN A2A discovery.
//!
//! This module defines the JSON-serializable message used by local-network A2A
//! discovery. A sender broadcasts a [`Beacon`] over UDP so nearby CodeTether
//! peers can learn a display name and the HTTP URL they should use to connect.
//!
//! Received beacons should be treated as untrusted network input. Use
//! [`Beacon::is_valid`] to filter payloads that do not carry this module's
//! protocol marker before acting on the advertised peer information.

use serde::{Deserialize, Serialize};

/// UDP port used for LAN A2A discovery beacons.
///
/// Peers participating in local discovery should send and listen for beacon
/// payloads on this port. The value is part of the discovery protocol
/// convention, so all peers must agree on it to discover each other.
pub const PORT: u16 = 47042;

/// Protocol marker embedded in every valid CodeTether A2A beacon.
///
/// This private marker helps distinguish CodeTether discovery payloads from
/// unrelated UDP traffic received on the same port.
const MAGIC: &str = "codetether-a2a-v1";

/// UDP discovery payload advertising a CodeTether A2A peer.
///
/// The payload includes a private protocol marker plus public peer metadata.
/// Beacons created with [`Beacon::new`] always include the expected marker.
/// Beacons deserialized from the network should be checked with
/// [`Beacon::is_valid`] before their fields are used.
///
/// # Invariants
///
/// `magic` should equal the module's protocol marker for payloads generated by
/// this version of the discovery code. The public `name` and `url` values are
/// caller-provided and are not authenticated by this type.
///
/// # Examples
///
/// /// use codetether_agent::a2a::beacon::Beacon;
///
/// let beacon = Beacon::new(
///     "desktop-worker".to_string(),
///     "http://192.168.1.10:8001".to_string(),
/// );
///
/// assert!(beacon.is_valid());
/// assert_eq!(beacon.name, "desktop-worker");
/// #[derive(Debug, Serialize, Deserialize)]
pub struct Beacon {
    /// Protocol marker used to validate that this payload belongs to A2A discovery.
    magic: String,
    /// Human-readable name of the announcing peer.
    ///
    /// This value is useful for logs and UI display, but it should not be
    /// treated as a stable identity or proof of authenticity.
    pub name: String,
    /// Contact URL advertised by the announcing peer.
    ///
    /// Other peers use this URL to initiate A2A communication after discovery.
    /// Because it may come from the network, callers should treat it as
    /// untrusted until a connection is successfully established.
    pub url: String,
}

impl Beacon {
    /// Creates a discovery beacon for a peer name and contact URL.
    ///
    /// # Arguments
    ///
    /// * `name` - Human-readable label for the peer sending the beacon.
    /// * `url` - HTTP endpoint other peers should use to contact the sender.
    ///
    /// # Returns
    ///
    /// A [`Beacon`] containing the provided metadata and this module's current
    /// protocol marker. The returned value passes [`Beacon::is_valid`].
    ///
    /// # Side Effects
    ///
    /// This function performs no I/O and has no network side effects. It only
    /// allocates and stores the beacon fields.
    pub fn new(name: String, url: String) -> Self {
        Self {
            magic: MAGIC.to_string(),
            name,
            url,
        }
    }

    /// Checks whether this beacon carries the expected discovery protocol marker.
    ///
    /// # Returns
    ///
    /// `true` if the beacon's private magic string matches the CodeTether A2A
    /// discovery marker for this module; otherwise `false`.
    ///
    /// # Side Effects
    ///
    /// This method is read-only and performs no I/O. It does not authenticate
    /// the sender, validate the URL, or prove the peer is reachable.
    pub fn is_valid(&self) -> bool {
        self.magic == MAGIC
    }
}
