//! Slash command hint descriptions for autocomplete.

pub const SLASH_HINTS: &[(&str, &str)] = &[
    (
        "/go ",
        "OKR-gated relay (requires approval, tracks outcomes)",
    ),
    ("/add ", "Easy mode: create a teammate"),
    ("/talk ", "Easy mode: message or focus a teammate"),
    ("/list", "Easy mode: list teammates"),
    ("/remove ", "Easy mode: remove a teammate"),
    ("/home", "Easy mode: return to main chat"),
    ("/help", "Open help"),
    ("/spawn ", "Create a named sub-agent"),
    ("/autochat ", "Tactical relay (fast path, no OKR tracking)"),
    (
        "/autochat-local ",
        "Tactical relay forced to local CUDA model",
    ),
    ("/local", "Switch active model to local CUDA"),
    ("/agents", "List spawned sub-agents"),
    ("/kill ", "Remove a spawned sub-agent"),
    ("/agent ", "Focus or message a spawned sub-agent"),
    ("/swarm ", "Run task in parallel swarm mode"),
    ("/ralph", "Start autonomous PRD loop"),
    ("/undo", "Undo last message and response"),
    ("/sessions", "Open session picker"),
    ("/resume", "Resume session or interrupted relay"),
    ("/new", "Start a fresh session"),
    ("/model", "Select or set model"),
    ("/file", "Open file picker or attach /file <path>"),
    ("/webview", "Switch to webview layout"),
    ("/classic", "Switch to classic layout"),
    ("/inspector", "Toggle inspector pane"),
    ("/refresh", "Refresh workspace"),
    ("/archive", "Show persistent chat archive path"),
    ("/view", "Toggle Chat/Swarm view"),
    ("/buslog", "Show protocol bus log"),
    ("/protocol", "Show protocol registry"),
];
