//! Math substitution table chunk 1 of 3 (see `super::message_formatter_math`).

/// LaTeX→Unicode pairs, applied longest-first.
pub(super) const PAIRS: &[(&str, &str)] = &[
    ("\\Rightarrow", "⇒"),
    ("\\Leftarrow", "⇐"),
    ("\\rightarrow", "→"),
    ("\\leftarrow", "←"),
    ("\\leftrightarrow", "↔"),
    ("\\mapsto", "↦"),
    ("\\mathbb{C}", "ℂ"),
    ("\\mathbb{R}", "ℝ"),
    ("\\mathbb{Z}", "ℤ"),
    ("\\mathbb{N}", "ℕ"),
    ("\\mathbb{Q}", "ℚ"),
    ("\\mathbb C", "ℂ"),
    ("\\mathbb R", "ℝ"),
    ("\\mathbb Z", "ℤ"),
    ("\\mathbb N", "ℕ"),
    ("\\mathbb Q", "ℚ"),
    ("\\otimes", "⊗"),
    ("\\oplus", "⊕"),
    ("\\times", "×"),
    ("\\cdot", "·"),
    ("\\cdots", "⋯"),
    ("\\ldots", "…"),
    ("\\dots", "…"),
    ("\\vdots", "⋮"),
    ("\\ddots", "⋱"),
    ("\\sum", "Σ"),
    ("\\prod", "∏"),
    ("\\int", "∫"),
    ("\\infty", "∞"),
    ("\\partial", "∂"),
    ("\\nabla", "∇"),
    ("\\forall", "∀"),
    ("\\exists", "∃"),
    ("\\nexists", "∄"),
    ("\\emptyset", "∅"),
];
