//! Math substitution table chunk 2 of 3 (see `super::message_formatter_math`).

/// LaTeX→Unicode pairs, applied longest-first.
pub(super) const PAIRS: &[(&str, &str)] = &[
    ("\\subset", "⊂"),
    ("\\subseteq", "⊆"),
    ("\\supset", "⊃"),
    ("\\supseteq", "⊇"),
    ("\\cup", "∪"),
    ("\\cap", "∩"),
    ("\\wedge", "∧"),
    ("\\vee", "∨"),
    ("\\neg", "¬"),
    ("\\lnot", "¬"),
    ("\\equiv", "≡"),
    ("\\approx", "≈"),
    ("\\sim", "∼"),
    ("\\simeq", "≃"),
    ("\\cong", "≅"),
    ("\\propto", "∝"),
    ("\\leq", "≤"),
    ("\\geq", "≥"),
    ("\\neq", "≠"),
    ("\\ne", "≠"),
    ("\\pm", "±"),
    ("\\mp", "∓"),
    ("\\sqrt", "√"),
    ("\\dim", "dim"),
    ("\\det", "det"),
    ("\\ker", "ker"),
    ("\\to", "→"),
    ("\\in", "∈"),
    ("\\notin", "∉"),
    ("\\ni", "∋"),
    ("\\alpha", "α"),
    ("\\beta", "β"),
    ("\\gamma", "γ"),
    ("\\delta", "δ"),
    ("\\epsilon", "ε"),
];
