//! Slash command constants used for autocomplete suggestions.

/// All recognized slash commands (including easy-mode aliases).
pub const SLASH_COMMANDS: &[&str] = &[
    "/help",
    "/sessions",
    "/swarm",
    "/ralph",
    "/bus",
    "/protocol",
    "/file",
    "/image",
    "/autoapply",
    "/network",
    "/autocomplete",
    "/ask",
    "/mcp",
    "/model",
    "/settings",
    "/lsp",
    "/rlm",
    "/latency",
    "/inspector",
    "/symbols",
    "/chat",
    "/new",
    "/keys",
    "/spawn",
    "/kill",
    "/agents",
    "/agent",
    "/add",
    "/talk",
    "/say",
    "/list",
    "/ls",
    "/remove",
    "/rm",
    "/focus",
    "/home",
    "/main",
    "/webview",
    "/classic",
    "/autochat",
    "/recall",
];
