use super::request::{
    AxiosRequest, ClickTextRequest, CloseTabRequest, DiagnoseRequest, EvalRequest, FetchRequest,
    FillRequest, KeyPressRequest, NavigationRequest, NetworkLogRequest, NewTabRequest,
    ScopeRequest, ScreenshotRequest, SelectorRequest, StartRequest, TabSelectRequest,
    ToggleRequest, TypeRequest, UploadRequest, WaitRequest, XhrRequest,
};

pub enum BrowserCommand {
    Health,
    Start(StartRequest),
    Stop,
    Snapshot,
    Goto(NavigationRequest),
    Back,
    Reload,
    Wait(WaitRequest),
    Click(SelectorRequest),
    Upload(UploadRequest),
    Fill(FillRequest),
    Type(TypeRequest),
    Press(KeyPressRequest),
    Text(ScopeRequest),
    Html(ScopeRequest),
    Eval(EvalRequest),
    ClickText(ClickTextRequest),
    FillNative(FillRequest),
    Toggle(ToggleRequest),
    Screenshot(ScreenshotRequest),
    MouseClick(super::request::PointerClick),
    KeyboardType(super::request::KeyboardTypeRequest),
    KeyboardPress(super::request::KeyboardPressRequest),
    Tabs,
    TabsSelect(TabSelectRequest),
    TabsNew(NewTabRequest),
    TabsClose(CloseTabRequest),
    NetworkLog(NetworkLogRequest),
    Fetch(FetchRequest),
    Axios(AxiosRequest),
    Xhr(XhrRequest),
    Diagnose(DiagnoseRequest),
}
