use super::request::{
    ClickTextRequest, CloseTabRequest, EvalRequest, FillRequest, KeyPressRequest,
    NavigationRequest, NewTabRequest, ScopeRequest, ScreenshotRequest, SelectorRequest,
    StartRequest, TabSelectRequest, ToggleRequest, TypeRequest, WaitRequest,
};

pub enum BrowserCommand {
    Health,
    Start(StartRequest),
    Stop,
    Snapshot,
    Console,
    Goto(NavigationRequest),
    Back,
    Reload,
    Wait(WaitRequest),
    Click(SelectorRequest),
    Fill(FillRequest),
    Type(TypeRequest),
    Press(KeyPressRequest),
    Text(ScopeRequest),
    Html(ScopeRequest),
    Eval(EvalRequest),
    ConsoleEval(EvalRequest),
    ClickText(ClickTextRequest),
    FillNative(FillRequest),
    Toggle(ToggleRequest),
    Screenshot(ScreenshotRequest),
    MouseClick(super::request::PointerClick),
    KeyboardType(super::request::KeyboardTypeRequest),
    KeyboardPress(super::request::KeyboardPressRequest),
    Tabs,
    TabsSelect(TabSelectRequest),
    TabsNew(NewTabRequest),
    TabsClose(CloseTabRequest),
}
