//! Error fragments that indicate a safe upstream retry.

pub(super) const RETRYABLE_NEEDLES: &[&str] = &[
    " 500 ",
    " 503 ",
    " 504 ",
    " 502 ",
    " 429 ",
    "status code 500",
    "status code 503",
    "status code 504",
    "status code 502",
    "status code 429",
    "internal server error",
    "service unavailable",
    "gateway timeout",
    "upstream request timeout",
    "server error: 500",
    "server error: 503",
    "server error: 504",
    "network error",
    "connection reset",
    "connection refused",
    "timed out",
    "timeout",
    "broken pipe",
    "unexpected eof",
    "flagged for possible",
    "content moderation",
    "content policy",
    "safety system",
    "refused to generate",
    "token_quota_exceeded",
    "too many tokens",
    "limit exceeded",
    "rate_limit",
    "ratelimit",
    "quota exceeded",
    "too many requests",
    "no choices",
    "empty response",
    "stream ended without producing any content",
    "stream ended without assistant content",
    "temporary provider availability issue",
    "servers are currently overloaded",
    "server_is_overloaded",
];
