mod claim;
mod commit_args;
mod git;
mod git_identity;
mod hook;
mod hook_chmod;
mod hook_path;
mod hook_script;
mod hook_seed;
mod identity;
mod repo;
mod signature;
mod trailer_identity;
mod trailer_optional;
mod trailer_run;
mod trailers;
mod types;

pub use claim::ClaimProvenance;
pub use commit_args::commit_args_with_signature_policy;
pub use git::{git_commit_with_provenance, git_commit_with_provenance_blocking};
pub use git_identity::git_identity_env_vars;
pub use hook::install_commit_msg_hook;
pub use hook_path::{commit_editmsg_path, repo_root};
pub use hook_script::commit_msg_hook_script;
pub use hook_seed::ensure_provenance_trailers;
pub use identity::{git_author_email, git_author_name};
pub use repo::enrich_from_repo;
pub use signature::sign_provenance;
pub use trailers::provenance_trailers;
pub use types::{ExecutionOrigin, ExecutionProvenance};
