//! Tools unavailable inside workspace-scoped swarm execution.

pub(super) const IDS: &[&str] = &[
    "question",
    "confirm_edit",
    "confirm_multiedit",
    "plan_enter",
    "plan_exit",
    "agent",
    "close_agent",
    "spawn_agent",
    "followup_task",
    "list_agents",
    "wait_agent",
    "interrupt_agent",
    "resume_agent",
    "send_input",
    "send_message",
    "swarm_execute",
    "relay_autochat",
    "ralph",
    "prd",
    "go",
    "undo",
    "kubernetes",
    "k8s_tool",
    "tetherscript_plugin",
    "diff",
];
