//! Literal interpreter invocations that must never reach process execution.

pub(super) const COMMANDS: &[&str] = &[
    "python --version",
    "python3 --version",
    "python3 script.py --flag",
    "python3 -m pytest tests/",
    "python3 -c 'print(1)'",
    "/usr/bin/python3.12 script.py",
    "'/opt/my venv/bin/python3' script.py",
    "env VAR=1 python3 script.py",
    "sudo -u root /usr/bin/python3 script.py",
    "timeout 10s python3 script.py",
    "command python3 script.py",
    "cd repo && python3 script.py",
    "echo ready; python3 script.py",
    "printf data | python3 script.py",
    "(python3 script.py)",
    "bash -lc 'python3 script.py'",
    "sh -c \"env python3 script.py\"",
    "pyt'hon3' script.py",
    "py\\thon3 script.py",
    "python3.exe script.py",
    "py\\\nthon3 script.py",
    "env -S 'python3 script.py'",
    "env --split-string=python3 script.py",
    "env --split-string 'python3 script.py'",
    "# comment\npython3 script.py",
    "echo $(python3 script.py)",
    "echo \"$(python3 script.py)\"",
    "echo `python3 script.py`",
    "echo \"`python3 script.py`\"",
    "echo \"$(sh -c 'python3 script.py')\"",
];
